// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.27.1
// source: media_search_engine.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "media";

export interface SearchMovieByNameRequest {
  name: string;
}

export interface SearchMovieByNameResponse {
  moviesList: Movie[];
}

export interface SearchSerieByNameRequest {
  name: string;
}

export interface SearchSerieByNameResponse {
  seriesList: Serie[];
}

export interface Movie {
  id: string;
  title: string;
  overview: string;
  releaseDate: string;
  posterPath: string;
  backdropPath: string;
  popularity: number;
}

export interface Serie {
  id: string;
  title: string;
  overview: string;
  startDate: string;
  endDate: string;
  runTime: number;
  numberOfEpisodes: number;
  posterPath: string;
  backdropPath: string;
  popularity: number;
}

export const MEDIA_PACKAGE_NAME = "media";

export interface MediaSearchEngineClient {
  searchMovieByName(request: SearchMovieByNameRequest): Observable<SearchMovieByNameResponse>;

  searchSerieByName(request: SearchSerieByNameRequest): Observable<SearchSerieByNameResponse>;
}

export interface MediaSearchEngineController {
  searchMovieByName(
    request: SearchMovieByNameRequest,
  ): Promise<SearchMovieByNameResponse> | Observable<SearchMovieByNameResponse> | SearchMovieByNameResponse;

  searchSerieByName(
    request: SearchSerieByNameRequest,
  ): Promise<SearchSerieByNameResponse> | Observable<SearchSerieByNameResponse> | SearchSerieByNameResponse;
}

export function MediaSearchEngineControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["searchMovieByName", "searchSerieByName"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MediaSearchEngine", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MediaSearchEngine", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MEDIA_SEARCH_ENGINE_SERVICE_NAME = "MediaSearchEngine";
